import type { Metadata } from 'next'
import './globals.css'
import { LeftPanel } from '@/components/Navbar/left_panel'
import { Inter, Geist } from 'next/font/google'
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={`${inter.className} antialiased bg-[#f9f9f9]`}>
        <LeftPanel />
        <div className="pl-66">{children}</div>
      </body>
    </html>
  )
}
