import type { Metadata } from 'next'
import './globals.css'
import { LeftPanel } from '@/components/Navbar/left_panel'
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: 'FocusFlow',
  description: 'Generated by FocusFlow',
}

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-[#f9f9f9]`}>
        <LeftPanel />
        <div className="pl-66">{children}</div>
      </body>
    </html>
  )
}
