import { redirect } from 'next/navigation'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'FocusFlow',
  description: 'Generated by FocusFlow',
}
export default async function HomePage() {
  return <main></main>
}
